### ISSUE TITLE
Have you compared your smpl annotations with the results by mosh?

### ISSUE THREAD

**Issue by shyanguan** [mks0601/I2L-MeshNet_RELEASE#13]
Hi @mks0601, thanks for your code and data! My question is whether you have compared your smpl fitting results with the one from mosh? For example, Kanazawa used to provide SMPL annotations of Human 3.6M which is computing using mosh. Which one is better?

**Comment by shyanguan** [comment]
BTW, Smplify is a time-consuming optimization method. Could you share some details to efficiently fitting large benchmarks, such as COCO?

**Comment by mks0601** [comment]
SMPL Mosh fit is not accessible because of the license issue :( It's been maybe more than 1 year? so I couldn't calculate the error of Mosh fit. I reported error of my SMPLify-X fit to my paper (Table 13. 13.1mm). Also, for the time, I divide the dataset into several chunks and ran it on each GPU. Or you can estimate initial parameters using neural network and reduce the number of iteration following SPIN.

**Comment by shyanguan** [comment]
Thanks for your help! I will try it!
