### ISSUE TITLE
Run on hands

### ISSUE THREAD

**Issue by FranciscoGomez90** [mks0601/I2L-MeshNet_RELEASE#27]
I am having trouble when running MeshNet + RootNet on hands.
I downloaded the rootnet model, from this repo and cloned rootnet. When I run the rootnet demo with the model provided here, an error is shown 
`RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.root.deconv_layers.0.weight", "module.root.deconv_layers.1.weight",....`
How can I run RootNet with the trained model you provide in this repo?
thank you.

**Comment by mks0601** [comment]
Hmm.. I haven't provided pre-trained RootNet in this repo? You should use RootNet repo in [here](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE).

**Comment by FranciscoGomez90** [comment]
Yes, but in the readme there is a part that states

FreiHAND dataset
    Download I2L-MeshNet trained on [FreiHand].
    Download bounding boxs and root joint coordinates (from RootNet) of [FreiHAND]. bbox is from Detectron2.

The Download I2L-MeshNet trained on [FreiHand] link (https://drive.google.com/drive/folders/1NGEScDf2tYtrloLGinqV97SRvfpSJ4o7) gives you two models: i2L-mesh and RootNet. Are these models the correct ones for hand pose estimation?
thanks

**Comment by mks0601** [comment]
Oh I forgot this. The RootNet in the drive is trained using my modified code so input normalization and the module names are slightly different. You should rename `module.root_net` keys in the snapshot file to `module.root` keys. Also, just normalize 0~255 image to 0~1 instead of using [this line](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE/blob/9e49e321ca1fefc68b6b265a727abc96af00367e/data/dataset.py#L72)

**Comment by FranciscoGomez90** [comment]
Could you please provide the complete rootnet you used?

**Comment by mks0601** [comment]
[3DMPPE-RootNet.zip](https://github.com/mks0601/I2L-MeshNet_RELEASE/files/5409239/3DMPPE-RootNet.zip)

I guess this would work, but not perfectly sure. Sorry I'm too busy to check this :(
