### ISSUE TITLE
Problems about Data set configuration

### ISSUE THREAD

**Issue by booker-max** [mks0601/I2L-MeshNet_RELEASE#50]
1. Is the "annotations" file in the MSCOCO folder under the “data” folder the "2017 Train/Val annotations" file or the "2017 Stuff Train/Val annotations" file
‘”
2. Where to download the "J_regressor_coco_hip_smpl.npy" file in the MSCOCO folder under the “data“ folder

3. Where should the Yolo.json file in the Humandetection result folder in the link https://drive.google.com/drive/folders/1fWrx0jnWzcudU6FN6QCZWefaOFSAadgR be placed and what does it do?

4. Can you send me a copy of the "images" folder under the Human36M folder and the "augmented_set" and "unaugmented_set" folders under the Muco folder. I can't download it in your shared link. "Download" will appear ”The file has exceeded the download limit, so it cannot be downloaded at this time", but I am really eager to get this data set to carry out my research work. Can you send a copy to my mailbox, 1654617276wj@gmail.com, very thank.

**Comment by mks0601** [comment]
1. I haven't used Stuff annotation files.
2. I cannot get your question. The file is already available in the [repo](https://github.com/mks0601/I2L-MeshNet_RELEASE/tree/master/data/MSCOCO).
3. You don't have to take care about that. Just follow the instruction of README.
4. Please read the README more carefully. That issue is already addressed in [here](https://github.com/mks0601/I2L-MeshNet_RELEASE#data).

**Comment by booker-max** [comment]
Thanks for the fast answer!This helped me a lot
